### Q-learning

In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
rewards=np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1,],
    [-1,0,0,-1,0,-1],
    [-1,0,0,-1,-1,100],
    [-1,0,-1,-1,0,100]
])

In [3]:
pd.DataFrame(rewards) #visualize the reward table

0  1  2  3  4    5
0 -1 -1 -1 -1  0   -1
1 -1 -1 -1  0 -1  100
2 -1 -1 -1  0 -1   -1
3 -1  0  0 -1  0   -1
4 -1  0  0 -1 -1  100
5 -1  0 -1 -1  0  100

In [4]:
def initialaze_q(m,n):
    return np.zeros((m,n))
q_matrix=initialaze_q(6,6)
pd.DataFrame(q_matrix)

0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0

In [5]:
a=[2,5,4,8]
for i in enumerate(a):
    print(i)

(0, 2)
(1, 5)
(2, 4)
(3, 8)


In [6]:
def set_initial_state(rooms=6):
    #set the initial state/rooms the agent initialize in
    return np.random.randint(0,rooms)


def get_action(current_state,reward_matrix):  #current_state=1    # agent irikinna roomilnn ethalla valid reeomsilek povan patum kand pidikin
    #Given a state ,choose from the possible actions
    valid_action=[]
    for action in enumerate(reward_matrix[current_state]):
        #action contains enumerate objects in the format action = (action,reward)
        #so action[1] denotes the reward at a particular state
        if action[1]!=-1:
            valid_action+= [action[0]]
    #choose a random action from the valid action
    return random.choice(valid_action) #valid_action=[3,5]

#updating q matrix
def take_action(current_state,reward_matrix,gamma,verbose=False):
    
    #tae a single action from the above function
    action=get_action(current_state,reward_matrix)  #3
    
    #currrent state-action reward
    cs_reward=reward_matrix[current_state,action]
    #next state -action reward (maximum of all possible rewards)
    ns_reward=max(q_matrix[action,])
    #implementation of of the q updation equation --(bellman equation)
    q_current_value=cs_reward + (gamma * ns_reward)
    
    
    q_matrix[current_state,action]=q_current_value # updating q matrix
    new_state = action #3
    if verbose:
        print(q_matrix)
        print(f'Old state: {current_state}| New state:{new_state}\n\n')
        if new_state==5:
            print(f"agent has reached it's goal!!")
    return new_state

In [7]:
def initialize_episode(reward_matrix , initial_state, gamma, verbose=False):
    
    # runs 1 episode until the agent reaches its goal
    current_state = initial_state
    while True: # always
        current_state = take_action(current_state , reward_matrix, gamma, verbose)
        # run until the goal is reached
        if current_state==5:
            break

def train_agent(iterations , reward_matrix , gamma, verbose=False):
    
    # runs a given no. of episodes then normalises the matrix
    print('Training in progress............')
    for episode in range(iterations):
        initial_state= set_initial_state()
        initialize_episode(reward_matrix, initial_state,gamma, verbose)
    print('Training complete!!')
    return q_matrix

def normalize_matrix (q_matrix):
    normalized_q = q_matrix/max(q_matrix[q_matrix.nonzero()])*100
    return normalized_q.astype(int)
            


In [8]:
# test run of a single episode
gamma= 0.1 # istulla value set cheyya
# here the initial_state is initialized to a value
# we can also use the set_initial_state()
initial_state= set_initial_state()
initialize_episode(rewards , initial_state , gamma, True) # vergoa=True

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 1| New state:3


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 3| New state:1


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 1| New state:3


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 3| New state:1


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 1| New state:3


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old state: 3| New state:1


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  

In [9]:
# test run of full training
# verbos false kodtha training process display chyth varoolaa # training kinja reward matrix venda
gamma= 0.8
# initial_state = set_initial_state()
# initial_action get_action(initial_state, rewards)
q_table= train_agent(2000, rewards, gamma , False)
pd.DataFrame(q_table)

Training in progress............
Training complete!!


0      1      2      3      4      5
0  0.0    0.0    0.0    0.0  400.0    0.0
1  0.0    0.0    0.0  320.0    0.0  500.0
2  0.0    0.0    0.0  320.0    0.0    0.0
3  0.0  400.0  256.0    0.0  400.0    0.0
4  0.0  400.0  256.0    0.0    0.0  500.0
5  0.0  400.0    0.0    0.0  400.0  500.0

In [10]:
normalised=pd.DataFrame(normalize_matrix(q_matrix))

In [11]:
normalised

0   1   2   3   4    5
0  0   0   0   0  80    0
1  0   0   0  64   0  100
2  0   0   0  64   0    0
3  0  80  51   0  80    0
4  0  80  51   0   0  100
5  0  79   0   0  79   99

In [12]:
# argmas --- maximum valuente index position kittan
# using the trained q table,  the agent can now find the best path to reach the goal
def deploy_agent(init_state, q_table):
    print('start:', init_state)
    state=init_state ##2
    steps=0
    while True:
        steps+=1 #3
        action=np.argmax(q_table[state,:]) # 1
        print(action)
        state = action #3
        if action==5:
            print('Finished!')
            return steps

In [17]:
start_room =2
steps = deploy_agent(start_room , q_table)
print('Number of rooms/actions:', steps)

start: 2
3
1
5
Finished!
Number of rooms/actions: 3
